SELECT  a.CUSTOMER_ID,
        w.MRN,
        w.TRAINING_STATUS,
        w.WARRANTY_START_DATE,
        w.WARRANTY_END_DATE
FROM (SELECT DISTINCT CUSTOMER_ID,MRN
      FROM CDH.PA_PATIENT_DETAILS_VW
      WHERE LATEST_PRODUCT = '670G') a
INNER JOIN PA_WARRANTY_DETAILS_VW w ON w.MRN = a.MRN
WHERE w.PRODUCT_MODEL_CATEGORY = '670G';
