SELECT a.CUSTOMER_ID,
       t.MRN,
       t.CREATED_DATE
FROM (SELECT DISTINCT CUSTOMER_ID, MRN
      FROM CDH.PA_PATIENT_DETAILS_VW
      WHERE LATEST_PRODUCT = '670G') a
INNER JOIN CDH.PA_PATIENT_TOUCHPOINT_VW t ON t.MRN = a.MRN;